### ISSUE TITLE
protospace-33386の実装

### ISSUE THREAD

**Issue by MIKIHISA-HIRAI** [MIKIHISA-HIRAI/protospace-33386#2]
実装完了しました

**Comment by takumi0530** [comment]
@MIKIHISA-HIRAI さん、ご提出ありがとうございます‼︎
動作の確認をいたしますので、**Protospaceの本番環境のURL**をコメントにて追記していただけますと幸いです。

追記が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
**※新しいissueを作っていただく必要はございません。**
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by MIKIHISA-HIRAI** [comment]
https://github.com/MIKIHISA-HIRAI/protospace-33386/issues/2
https://github.com/MIKIHISA-HIRAI/protospace-33386
でいいですか？

やり方がよくわかりません

**Comment by keisukekodama** [comment]
@MIKIHISA-HIRAI さん、ご提出ありがとうございます‼︎

作成したProtospaceがインターネット上で確認できるURLの添付をお願いします。
そのURLからProtoSpaceの動作確認を行います。
やりかたがわからない場合はメンターへ質問をしましょう！

追記が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by MIKIHISA-HIRAI** [comment]
https://protospace-33386.herokuapp.com/
お願いします
